// Copyright 2026 boshenzh. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newTradePromotedCmd(flags *rootFlags) *cobra.Command {
	var flagReporterCode int
	var flagPartnerCode int
	var flagPeriod string
	var flagCmdCode string
	var flagFlowCode string
	var flagMotCode int
	var flagCustomsCode string
	var flagMaxRecords int

	cmd := &cobra.Command{
		Use:   "trade",
		Short: "Fetch annual trade-flow records (no auth, ~500 records max).",
		Long:  "Shortcut for 'trade preview'. Fetch annual trade-flow records (no auth, ~500 records max).",
		Example: "  webprofile-pp-cli trade --reporter-code 42",
		Annotations: map[string]string{"pp:endpoint": "trade.preview", "pp:method": "GET", "pp:path": "/public/v1/preview/C/A/HS", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("reporter-code") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "reporter-code")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/public/v1/preview/C/A/HS"
			params := map[string]string{}
			if flagReporterCode != 0 {
				params["reporterCode"] = fmt.Sprintf("%v", flagReporterCode)
			}
			if flagPartnerCode != 0 {
				params["partnerCode"] = fmt.Sprintf("%v", flagPartnerCode)
			}
			if flagPeriod != "" {
				params["period"] = fmt.Sprintf("%v", flagPeriod)
			}
			if flagCmdCode != "" {
				params["cmdCode"] = fmt.Sprintf("%v", flagCmdCode)
			}
			if flagFlowCode != "" {
				params["flowCode"] = fmt.Sprintf("%v", flagFlowCode)
			}
			if flagMotCode != 0 {
				params["motCode"] = fmt.Sprintf("%v", flagMotCode)
			}
			if flagCustomsCode != "" {
				params["customsCode"] = fmt.Sprintf("%v", flagCustomsCode)
			}
			if flagMaxRecords != 0 {
				params["maxRecords"] = fmt.Sprintf("%v", flagMaxRecords)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "trade", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagReporterCode, "reporter-code", 0, "Reporter (importer) country numeric code (e.g. 818 = Egypt, 156 = China, 842 = USA). Use `webprofile-pp-cli...")
	cmd.Flags().IntVar(&flagPartnerCode, "partner-code", 0, "Partner (exporter) country code (e.g. 156 = China, 0 = world). Default 0 if omitted.")
	cmd.Flags().StringVar(&flagPeriod, "period", "", "Year (e.g. '2023') or comma-separated years ('2021,2022,2023'). Default last full year.")
	cmd.Flags().StringVar(&flagCmdCode, "cmd-code", "", "HS commodity code (2-digit chapter to 6-digit detail; e.g. '8517' for telephones, '6109' for T-shirts). Default 'TOTAL'.")
	cmd.Flags().StringVar(&flagFlowCode, "flow-code", "M", "Trade flow: M=imports, X=exports, MIP=re-imports, XIP=re-exports. Default M.")
	cmd.Flags().IntVar(&flagMotCode, "mot-code", 0, "Mode of transport (0=all). Defaults to all modes.")
	cmd.Flags().StringVar(&flagCustomsCode, "customs-code", "C00", "Customs procedure (C00=all). Defaults to all.")
	cmd.Flags().IntVar(&flagMaxRecords, "max-records", 500, "Max records to return (preview is capped at ~500).")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
