// Copyright 2026 boshenzh. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCarrierServicesPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyPortCode string
	var bodyCarrierCode string

	cmd := &cobra.Command{
		Use:   "carrier-services",
		Short: "Continent → service map for a (port, carrier) pair.",
		Long:  "Shortcut for 'carrier_services list'. Continent → service map for a (port, carrier) pair.",
		Example: "  schedule-pp-cli carrier-services --port-code CNNSA --carrier-code CMA",
		Annotations: map[string]string{"pp:endpoint": "carrier_services.list", "pp:method": "POST", "pp:path": "/api/getCarrierServices", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("port-code") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "port-code")
			}
			if !cmd.Flags().Changed("carrier-code") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "carrier-code")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/getCarrierServices"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyPortCode != "" {
				body["portCode"] = bodyPortCode
			}
			if bodyCarrierCode != "" {
				body["carrierCode"] = bodyCarrierCode
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyPortCode, "port-code", "", "Weiyun port code.")
	cmd.Flags().StringVar(&bodyCarrierCode, "carrier-code", "", "Carrier code.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
