// Copyright 2026 boshenzh. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newFleetRoutesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagStartPortCode string
	var flagCarrier string

	cmd := &cobra.Command{
		Use:   "fleet-routes",
		Short: "Service lines (e.g. REX2, BEX, MEX) that a carrier runs out of the given port, grouped by destination region.",
		Long:  "Shortcut for 'fleet_routes list'. Service lines (e.g. REX2, BEX, MEX) that a carrier runs out of the given port, grouped by destination region.",
		Example: "  schedule-pp-cli fleet-routes --start-port-code example-value --carrier example-value",
		Annotations: map[string]string{"pp:endpoint": "fleet_routes.list", "pp:method": "GET", "pp:path": "/api/homePage/getFleetRoutes", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("start-port-code") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "start-port-code")
			}
			if !cmd.Flags().Changed("carrier") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "carrier")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/homePage/getFleetRoutes"
			params := map[string]string{}
			if flagStartPortCode != "" {
				params["startPortCode"] = fmt.Sprintf("%v", flagStartPortCode)
			}
			if flagCarrier != "" {
				params["carrier"] = fmt.Sprintf("%v", flagCarrier)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "fleet_routes", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagStartPortCode, "start-port-code", "", "Weiyun port code (e.g. 'CNNSA').")
	cmd.Flags().StringVar(&flagCarrier, "carrier", "", "Carrier company code (e.g. 'CMA', 'COSCO', 'PIL').")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
