// Copyright 2026 boshenzh. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/boshenzh/ocean-pp-cli/webprofile-pp-cli/internal/cli"
	"github.com/boshenzh/ocean-pp-cli/webprofile-pp-cli/internal/client"
	"github.com/boshenzh/ocean-pp-cli/webprofile-pp-cli/internal/config"
	"github.com/boshenzh/ocean-pp-cli/webprofile-pp-cli/internal/mcp/cobratree"
	"github.com/boshenzh/ocean-pp-cli/webprofile-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("reporters_list",
			mcplib.WithDescription("Fetch the full Comtrade reporter (country) reference file. Returns the ReportersResponse."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/files/v1/app/reference/Reporters.json", []mcpParamBinding{ }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("trade_preview",
			mcplib.WithDescription("Fetch annual trade-flow records (no auth, ~500 records max). Required: reporterCode. Optional: partnerCode (default: 0), period, cmdCode (plus 4 more). Returns the TradeResponse."),
			mcplib.WithString("reporterCode", mcplib.Required(), mcplib.Description("Reporter (importer) country numeric code (e.g. 818 = Egypt, 156 = China, 842 = USA). Use `webprofile-pp-cli...")),
			mcplib.WithString("partnerCode", mcplib.Description("Partner (exporter) country code (e.g. 156 = China, 0 = world). Default 0 if omitted.")),
			mcplib.WithString("period", mcplib.Description("Year (e.g. '2023') or comma-separated years ('2021,2022,2023'). Default last full year.")),
			mcplib.WithString("cmdCode", mcplib.Description("HS commodity code (2-digit chapter to 6-digit detail; e.g. '8517' for telephones, '6109' for T-shirts). Default 'TOTAL'.")),
			mcplib.WithString("flowCode", mcplib.Description("Trade flow: M=imports, X=exports, MIP=re-imports, XIP=re-exports. Default M.")),
			mcplib.WithString("motCode", mcplib.Description("Mode of transport (0=all). Defaults to all modes.")),
			mcplib.WithString("customsCode", mcplib.Description("Customs procedure (C00=all). Defaults to all.")),
			mcplib.WithString("maxRecords", mcplib.Description("Max records to return (preview is capped at ~500).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/public/v1/preview/C/A/HS", []mcpParamBinding{{PublicName: "reporterCode", WireName: "reporterCode", Location: "query"},{PublicName: "partnerCode", WireName: "partnerCode", Location: "query"},{PublicName: "period", WireName: "period", Location: "query"},{PublicName: "cmdCode", WireName: "cmdCode", Location: "query"},{PublicName: "flowCode", WireName: "flowCode", Location: "query"},{PublicName: "motCode", WireName: "motCode", Location: "query"},{PublicName: "customsCode", WireName: "customsCode", Location: "query"},{PublicName: "maxRecords", WireName: "maxRecords", Location: "query"}, }, []string{ }),
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT only). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      Run 'webprofile-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      Run 'webprofile-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "webprofile-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "webprofile-pp-cli", "data.db")
}
// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	// Block write operations
	upper := strings.ToUpper(strings.TrimSpace(query))
	for _, prefix := range []string{"INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE"} {
		if strings.HasPrefix(upper, prefix) {
			return mcplib.NewToolResultError("only SELECT queries are allowed"), nil
		}
	}

	db, err := store.OpenWithContext(ctx, dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "webprofile",
		"description": "A single-binary CLI for UN Comtrade trade-flow data — converts country names and HS descriptions into numeric...",
		"archetype":   "generic",
		"tool_count":  2,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion webprofile-pp-cli binary.",
		"resources": []map[string]any{
			{
				"name": "reporters",
				"description": "Country reference data (numeric Comtrade code, ISO3, name)",
				"endpoints": []string{"list",  },
				"syncable": true,
			},
			{
				"name": "trade",
				"description": "UN Comtrade trade-flow data",
				"endpoints": []string{"preview",  },
				"searchable": true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Country lookup", "command": "country", "description": "Fuzzy-search Comtrade country reporters by name, ISO2, ISO3, or numeric code.", "rationale": "Local cache of the public Reporters reference avoids 60K-row downloads on every lookup.", "via": "mcp-command-mirror"},
			{"name": "HS code search", "command": "hs-search", "description": "Fuzzy-search HS6 commodity codes by code prefix or text description.", "rationale": "Local cache of the H6 reference (~50K rows) makes HS lookups instant after the first run.", "via": "mcp-command-mirror"},
			{"name": "Annual import volumes", "command": "who-imports", "description": "Annual import volume for a country/HS pair from a specific partner (default China).", "rationale": "Resolves country and partner names to numeric codes locally, queries Comtrade preview, aggregates per-year...", "via": "mcp-command-mirror"},
			{"name": "Composite prospect-fit score", "command": "fit-score", "description": "0-100 score combining China-share of imports, year-over-year growth, and route coverage.", "rationale": "Three Comtrade calls + a hardcoded covered-lane portfolio produce a single number suitable for ranking prospects.", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Country lookup", "insight": "Local cache of the public Reporters reference avoids 60K-row downloads on every lookup."},
			{"topic": "HS code search", "insight": "Local cache of the H6 reference (~50K rows) makes HS lookups instant after the first run."},
			{"topic": "Annual import volumes", "insight": "Resolves country and partner names to numeric codes locally, queries Comtrade preview, aggregates per-year primaryValue and netWgt."},
			{"topic": "Composite prospect-fit score", "insight": "Three Comtrade calls + a hardcoded covered-lane portfolio produce a single number suitable for ranking prospects."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
