// Copyright 2026 boshenzh. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"


type HSCode struct {
	Id string `json:"id"`
	Text string `json:"text"`
}

type HSResponse struct {
	Results json.RawMessage `json:"results"`
}

type Reporter struct {
	Id string `json:"id"`
	Text string `json:"text"`
	ReporterCode int `json:"reporterCode"`
	ReporterDesc string `json:"reporterDesc"`
	ReporterCodeIsoAlpha2 string `json:"reporterCodeIsoAlpha2"`
	ReporterCodeIsoAlpha3 string `json:"reporterCodeIsoAlpha3"`
}

type ReportersResponse struct {
	Results json.RawMessage `json:"results"`
}

type TradeResponse struct {
	Count int `json:"count"`
	Data json.RawMessage `json:"data"`
	Error string `json:"error"`
}

type TradeRow struct {
	Period string `json:"period"`
	RefYear int `json:"refYear"`
	ReporterCode int `json:"reporterCode"`
	PartnerCode int `json:"partnerCode"`
	CmdCode string `json:"cmdCode"`
	FlowCode string `json:"flowCode"`
	Cifvalue float64 `json:"cifvalue"`
	Fobvalue float64 `json:"fobvalue"`
	PrimaryValue float64 `json:"primaryValue"`
	NetWgt float64 `json:"netWgt"`
	Qty float64 `json:"qty"`
	QtyUnitAbbr string `json:"qtyUnitAbbr"`
}
