// Copyright 2026 boshenzh. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"


type SCFIData struct {
	CurrentDate string `json:"currentDate"`
	LastDate string `json:"lastDate"`
	LineDataList json.RawMessage `json:"lineDataList"`
}

type SCFILine struct {
	Properties json.RawMessage `json:"properties"`
	CurrentContent float64 `json:"currentContent"`
	LastContent float64 `json:"lastContent"`
	Absolute float64 `json:"absolute"`
	Percentage float64 `json:"percentage"`
	DataItemTypeName string `json:"dataItemTypeName"`
}

type SCFIProperties struct {
	LineNameEN string `json:"lineName_EN"`
	LineNameZH string `json:"lineName_ZH"`
	UnitEN string `json:"unit_EN"`
	UnitZH string `json:"unit_ZH"`
	WeightingEN string `json:"weighting_EN"`
	WeightingZH string `json:"weighting_ZH"`
}

type SCFIResponse struct {
	Data json.RawMessage `json:"data"`
}
