// Copyright 2026 boshenzh. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"


type Carrier struct {
	CompanyCode string `json:"companyCode"`
	CompanyEnName string `json:"companyEnName"`
	CompanyShort string `json:"companyShort"`
	PinyinSearch string `json:"pinyinSearch"`
}

type CarrierListResponse struct {
	Success bool `json:"success"`
	Code int `json:"code"`
	Result json.RawMessage `json:"result"`
}

type CarrierServicesResponse struct {
	Success bool `json:"success"`
	Code int `json:"code"`
	Result json.RawMessage `json:"result"`
}

type ContinentServices struct {
	ContinentID int `json:"continentID"`
	ContinentCnName string `json:"continentCnName"`
	ContinentEnName string `json:"continentEnName"`
	Services json.RawMessage `json:"services"`
}

type CountryPortGroup struct {
	CountryCnName string `json:"countryCnName"`
	StartPorts json.RawMessage `json:"startPorts"`
}

type FleetRoute struct {
	FleetId int `json:"fleetId"`
	FleetName string `json:"fleetName"`
	RouteCode string `json:"routeCode"`
	PinyinSearch string `json:"pinyinSearch"`
}

type FleetRoutesResponse struct {
	Success bool `json:"success"`
	Code int `json:"code"`
	Result json.RawMessage `json:"result"`
}

type Port struct {
	Id int `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
	EnName string `json:"enName"`
	RegionCode string `json:"regionCode"`
	RegionEnName string `json:"regionEnName"`
	NameFormatter string `json:"nameFormatter"`
	PinyinSearch string `json:"pinyinSearch"`
}

type PortListResponse struct {
	Success bool `json:"success"`
	Code int `json:"code"`
	Result json.RawMessage `json:"result"`
}

type RegionGroup struct {
	Name string `json:"name"`
	Sort int `json:"sort"`
	FleetRoutes json.RawMessage `json:"fleetRoutes"`
}

type Service struct {
	ServiceID int `json:"serviceID"`
	ServiceCnName string `json:"serviceCnName"`
	ServiceEnName string `json:"serviceEnName"`
	PinyinSearch string `json:"pinyinSearch"`
}
